dist: trusty
language: cpp

# safelist
branches:
  only:
  - master
  - dev

compiler:
  - gcc

cache: ccache
sudo: required
services:
  - redis-server
os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
     # - gcc-4.8
     # - g++-4.8
  sonarcloud:
    organization: "max-cong" # the key of the org you chose at step #3
    projectKey: "max-cong_medis"
    project: "medis"

    token:
      secure: "get1DoumRkai7SbqBw5kWe8b2fEuBRvD5iDzMFQcxX7KRZrZuSYO2LZspZjCHv6pyFuBLVxNbanyESVZr9h8Qe6oORtFoNviVsgA7lPTCWtT/5ylJP2N98xA0aIHbaQ1RsDvacE29hxJVueNe6JfHzbLDcJq7GMHXiCcSk75PSl6E3OShuoKtLeoq/E4cXMm3f5LYh1DmeXs6PClEyZYXSkl1rIiGyhgCezcyJFgC5VTRpeien3Vs4Z/RrLyj7WNwSKM/NtB9YGS5mAHHxDNgXT5QnYRP8v/PTlhDGxmB218w5QI4BloD3aGQ0HzPtnR7FfIMbLqehG5gd5dbks64XVsjrLBtAOrwIU7HykUtqXPFUeYTHMbdhf0nArJlGgMlu29M2sR5OP30Vco8auFRG6PKzkN9wF2ats0aZtq+k2jN98EGUMUgP4l4LvZIR2Ze/PKTAPj6Hse0aEdXwxd7TVf2b1boH0DRfoKJ5h58HCKOHpItqxnxGTV6B8jxxE5oKvWtfYDfl+FXmxNwK4D0eqWssGbjcMkJvy6xitMTTYvHJfGtCBz3U1qN4dFnVP4o5Xf6NqDmlfLe3lmucpH5cdAHmkITvIuJNK6R4lv/l2PKYy1NL0WP+43McnWvJToIYTcVXxmMKp2K2tnPS3uPYqKTRYwDWCWXXe6g3W9+0A="



before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y valgrind cmake
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libevent-dev
  - export BASE_DIR=$PWD
  # the hiredis in the travis ci(sudo apt-cache search hiredis) is 0.10.0, that is too old, install the v0.14.0 instead
  - git clone https://github.com/redis/hiredis.git&&cd hiredis&&git checkout v0.14.0&&make&&sudo make install
  #- sudo apt-get install libgtest-dev this is not work, install it by hand
  - cd "${TRAVIS_BUILD_DIR}"
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  - sudo tar xf release-1.7.0.tar.gz
  - cd googletest-release-1.7.0
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - which valgrind
  - cd "${TRAVIS_BUILD_DIR}"
install:
  

before_script:



script: 
  - export LD_LIBRARY_PATH=/usr/local/lib
  - export GCOV_DIR=$PWD/build/tst/CMakeFiles/_medis_tests.dir
  - mkdir -p build &&mkdir -p gcov&& cd build
  - cmake -DCODE_COVERAGE=ON -DBUILD_TESTING=ON ..&&make clean all&&bin/medis_tests
  - cd $GCOV_DIR&& gcov -a tst.cpp.gcno
  - cp * $BASE_DIR/gcov/
  - cd $BASE_DIR/build&&rm -rf *&&cmake -DBUILD_TESTING=ON ..  &&build-wrapper-linux-x86-64 --out-dir ../bw-output make clean all&&bin/medis_tests
  - cd $BASE_DIR&& sonar-scanner -Dsonar.projectKey=max-cong_medis -Dsonar.projectName=medis -Dsonar.projectVersion=1.0 -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.sources=. -Dsonar.cfamily.gcov.reportsPath=gcov/ -Dsonar.coverage.exclusions=example/**/*,tst/**/* sonar.exclusions=example/**/*,tst/**/*
